language: node_js
node_js:
  - '5.1'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-gulp-requirejs' ]; then cd .. && eval "mv $currentfolder generator-gulp-requirejs" && cd generator-gulp-requirejs; fi
